# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4


    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "install dependencies"
          command: |
            echo $CIRCLE_NODE_INDEX
            cat /proc/sys/kernel/hostname
            cat /etc/hostname
            pwd
      - run:
          name: "Creating Dummy Artifacts"
          command: |
            echo "Test artifact file" > ~/repo/artifact-1
            mkdir ~/repo/artifacts;
            echo "Test artifact files in a dir" > ~/repo/artifacts/artifact-2;
          # command: "python run.py login.jmx qa.properties"

      - store_artifacts:
          path: ~/repo/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: ~/repo/artifacts
